dist: xenial
language: generic

addons:
  apt:
    packages:
      - python3-pip
      - python3-setuptools

services:
  - postgresql
  - docker

before_install:
  - pip3 install --upgrade pip

install:
  - npm --prefix ./frontend install
  - pip3 install --user -r backend/requirements.txt

before_script:
  - cp config.py.sample ./backend/config.py
  - psql -c "CREATE USER healthcheck WITH PASSWORD 'healthcheck';" -U postgres
  - psql -c "CREATE DATABASE healthcheck;" -U postgres

script:
  - npm --prefix ./frontend test
  - python3 -m unittest discover -s ./backend/tests

before_deploy:
  - docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD"
  - docker-compose build

deploy:
  provider: script
  script: docker-compose push
  on:
    branch: develop
