version: '3'

services:

    backend:
        restart: always
        image: backend
        build: ./backend
        volumes:
            - "./backend:/srv/www/backend"

    frontend:
        restart: always
        image: frontend
        build: ./frontend
        ports:
            - 8080:80
        volumes:
            - "./nginx.conf:/etc/nginx/conf.d/nginx.conf"
        depends_on:
            - backend
