version: '3'

services:

    backend:
        restart: always
        image: backend
        build: ./backend

    frontend:
        restart: always
        image: frontend
        build:
            context: .
            dockerfile: ./frontend/Dockerfile
        ports:
            - 8080:80
        depends_on:
            - backend
