export const SET_USER = "SET_USER";
export const LOGOUT = "LOGOUT";
export const OPTION_SELECTED = "OPTION_SELECTED";
export const QUESTION_ANSWERED = "QUESTION_ANSWERED";

export const SET_EDITORS = "SET_EDITORS";
export const ADD_EDITOR = "ADD_EDITOR";
export const DELETE_EDITOR = "DELETE_EDITOR";

export const SET_TRIBES = "SET_TRIBES";
export const SET_TRIBE_EDITORS = "SET_TRIBE_EDITORS";
export const SET_TRIBE_TEAMS = "SET_TRIBE_TEAMS";
export const ADD_TRIBE = "ADD_TRIBE";
export const DELETE_TRIBE = "DELETE_TRIBE";

export const SET_TEAM_MANAGERS = "SET_TEAM_MANAGERS";
export const SET_TEAM_MEMBERS = "SET_TEAM_MEMBERS";

export const OPEN_LOGIN_MODAL = "OPEN_LOGIN_MODAL";
export const CLOSE_LOGIN_MODAL = "CLOSE_LOGIN_MODAL ";
