//user and menu
export const SET_USER = "SET_USER";
export const SET_USER_TEAMS_DETAILS = "SET_USER_TEAMS_DETAILS";
export const SET_USER_MANAGING_DETAILS = "SET_USER_MANAGING_DETAILS";
export const SET_USER_TRIBES_DETAILS = "SET_USER_TRIBES_DETAILS";
export const SET_USER_EDITING_DETAILS = "SET_USER_EDITING_DETAILS";
export const LOGOUT = "LOGOUT";
export const OPTION_SELECTED = "OPTION_SELECTED";
export const OPEN_LOGIN_MODAL = "OPEN_LOGIN_MODAL";
export const CLOSE_LOGIN_MODAL = "CLOSE_LOGIN_MODAL ";

//admin panel
export const SET_EDITORS = "SET_EDITORS";
export const ADD_EDITOR = "ADD_EDITOR";
export const DELETE_EDITOR = "DELETE_EDITOR";

//tribes management
export const SET_TRIBES = "SET_TRIBES";
export const SET_TRIBE_EDITORS = "SET_TRIBE_EDITORS";
export const SET_TEAMS_IN_TRIBE = "SET_TEAMS_IN_TRIBE";

export const ADD_TRIBE = "ADD_TRIBE";
export const DELETE_TRIBE = "DELETE_TRIBE";
export const UPDATE_TRIBE_NAME = "UPDATE_TRIBE_NAME";
export const ADD_EDITOR_TO_TRIBE = "ADD_EDITOR_TO_TRIBE";
export const DELETE_EDITOR_FROM_TRIBE = "DELETE_EDITOR_FROM_TRIBE";
export const ADD_TEAM_TO_TRIBE = " ADD_TEAM_TO_TRIBE";

export const SET_TEAM_MANAGERS = "SET_TEAM_MANAGERS";
export const SET_TEAM_MEMBERS = "SET_TEAM_MEMBERS";

export const DELETE_TEAM = "DELETE_TEAM";
export const UPDATE_TEAM_NAME = "UPDATE_TEAM_NAME";
export const ADD_MANAGER_TO_TEAM = "ADD_MANAGER_TO_TEAM";
export const DELETE_MANAGER_FROM_TEAM = "DELETE_MANAGER_FROM_TEAM";
export const ADD_MEMBER_TO_TEAM = " ADD_MEMBER_TO_TEAM";
export const DELETE_MEMBER_FROM_TEAM = " DELETE_MEMBER_FROM_TEAM";

//edit survey
export const SET_ACTIVE_SURVEY = "SET_ACTIVE_SURVEY";
export const SET_NEXT_SURVEY = "SET_NEXT_SURVEY";
export const SET_DRAFT_SURVEY = "SET_DRAFT_SURVEY";
export const RESET_SURVEYS = "RESET_SURVEYS";
export const SET_SURVEYS_ARE_LOADING = "SET_SURVEYS_ARE_LOADING";
export const DELETE_SURVEY = "DELETE_SURVEY";

export const SET_DRAFT_SURVEY_PERIOD = "SET_DRAFT_SURVEY_PERIOD";
export const ADD_QUESTION_TO_DRAFT_SURVEY = "ADD_QUESTION_TO_DRAFT_SURVEY";
export const DELETE_QUESTION_FROM_DRAFT_SURVEY =
  "DELETE_QUESTION_FROM_DRAFT_SURVEY";
export const UPDATE_QUESTION_IN_DRAFT_SURVEY =
  "UPDATE_QUESTION_IN_DRAFT_SURVEY";

//fill survey
export const SET_CURRENT_SURVEY = "SET_CURRENT_SURVEY";
export const SET_CURRENT_SURVEY_TEAM_ID = "SET_CURRENT_SURVEY_TEAM_ID";
export const SET_QUESTION_ANSWER = "SET_QUESTION_ANSWER";
export const SET_QUESTION_COMMENT = "SET_QUESTION_COMMENT";
export const SET_CURRENT_SURVEY_IS_LOADING = "SET_CURRENT_SURVEY_IS_LOADING";

// Answers
export const SET_TEAM_ANSWERS = "SET_ANSWERS";
export const SET_TRIBE_MATRIX = "SET_TRIBE_MATRIX";
export const RESET_TRIBE_MATRIX = "RESET_TRIBE_MATRIX";
export const SET_TRIBE_HISTORY = "SET_TRIBE_HISTORY";
export const SET_TRIBE_PERIODS = "SET_TRIBE_PERIODS";
