"""empty message

Revision ID: 9caea0f07721
Revises: a060c3261b67
Create Date: 2019-08-06 13:40:10.168801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9caea0f07721'
down_revision = 'a060c3261b67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('deleted_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'deleted_at')
    # ### end Alembic commands ###
