"""empty message

Revision ID: 27a920cd3787
Revises: 9caea0f07721
Create Date: 2020-03-18 12:25:34.282943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a920cd3787'
down_revision = '9caea0f07721'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_users', sa.Column('management', sa.Boolean(), nullable=False, server_default = 'false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_users', 'management')
    # ### end Alembic commands ###
